import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';
import axios from 'axios';
import { fileURLToPath } from 'url';

export const generateReport = async (req, res) => {
  const { patientId, diagnosis, confidence, views, date, heatmapUrls } = req.body;

  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  const fileName = `ACL_Report_${patientId || Date.now()}.pdf`;

  // Use import.meta.url to get the current directory
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const reportsDir = path.join(__dirname, '..', 'reports');

  // Ensure the reports directory exists
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const filePath = path.join(reportsDir, fileName);
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // === FUTURISTIC HEADER ===
  doc.fillColor('#0077ff').fontSize(28).text('ACLyze AI', { align: 'center', underline: true });
  doc.moveDown(0.5);
  doc.fillColor('#444').fontSize(16).text('MRI-Based ACL Diagnosis Report', { align: 'center', underline: true });
  doc.moveDown();

  // === PATIENT & DIAGNOSIS INFO ===
  doc.fillColor('black').fontSize(12);
  doc.text(`Patient ID: ${patientId}`);
  doc.text(`Date: ${date || new Date().toLocaleDateString()}`);
  doc.text(`Diagnosis: ${diagnosis}`, { underline: true });
  doc.text(`AI Confidence Score: ${confidence}%`);
  doc.text(`Views Uploaded: ${views.join(', ')}`);
  doc.moveDown();

  // === DISCLAIMER ===
  doc.fillColor('red').fontSize(12).text('This report is for backup purposes only. Please consult a healthcare professional for a comprehensive diagnosis.', { align: 'center' });
  doc.moveDown();

  // === HEATMAPS SECTION ===
  if (heatmapUrls && heatmapUrls.length > 0) {
    doc.fillColor('#0077ff').fontSize(16).text('AI Heatmap Visualizations', { underline: true });
    doc.moveDown(0.5);

    for (let url of heatmapUrls) {
      try {
        const imgResponse = await axios.get(url, { responseType: 'arraybuffer' });
        const buffer = Buffer.from(imgResponse.data, 'base64');
        doc.image(buffer, { fit: [450, 300], align: 'center', valign: 'center' });
        doc.moveDown();
      } catch (err) {
        doc.fillColor('red').text('Failed to load image from Cloudinary.');
      }
    }
  }

  // === FOOTER ===
  doc.fillColor('#999').fontSize(10).text('Generated by ACLyze AI – Empowering Diagnostics with Intelligence', {
    align: 'center',
    baseline: 'bottom'
  });
  doc.moveDown();
  doc.fillColor('#0077ff').fontSize(12).text('Signature: ACLyze', { align: 'right' });

  doc.end();

  stream.on('finish', () => {
    // Set headers to suggest download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    res.sendFile(filePath);
  });
};